# -*- mode: python ; coding: utf-8 -*-

analysis = Analysis(
    ["app.py"],
    pathex=[],
    binaries=[],
    datas=[("models/*.pt", "models")],
    hiddenimports=["tkinter", "tkinter.ttk", "tkinter.messagebox"],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "pygame",
        "mujoco",
        "tensorflow",
        "matplotlib",
        "scipy",
        "IPython",
        "jupyter",
        "notebook",
        "zmq",
        "pandas",
        "sklearn",
        "PIL",
        "torchvision",
        "torchaudio",
        "torchtext",
    ],
    noarchive=False,
    optimize=1,
)
pyz = PYZ(analysis.pure)
exe = EXE(
    pyz,
    analysis.scripts,
    analysis.binaries,
    analysis.datas,
    [],
    name="RLArcade",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    onefile=True,
)
